apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-api
  labels:
    app: authentication-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-api
          image: docker.pkg.github.com/tenlastic/open-platform/authentication-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
