apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-api
  labels:
    app: authentication-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-api
          image: tenlastic/authentication-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
          envFrom:
            - secretRef:
                name: authentication-api-environment-variables
      imagePullSecrets:
        - name: githubimagepullsecret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
