apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: authentication-api-mongodb
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: authentication-api-mongodb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mongodb
    version: 7.4.6
  values:
    ## Global Docker image parameters
    ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
    ## Current available global Docker image parameters: imageRegistry and imagePullSecrets
    ##

    image:
      ## Bitnami MongoDB registry
      ##
      registry: docker.io
      ## Bitnami MongoDB image name
      ##
      repository: bitnami/mongodb
      ## Bitnami MongoDB image tag
      ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
      ##
      tag: 4.0.13-debian-9-r22
      ## Specify a imagePullPolicy
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent

      ## Set to true if you would like to see extra information on logs
      ## It turns on Bitnami debugging in minideb-extras-base
      ## ref:  https://github.com/bitnami/minideb-extras-base
      debug: false

    ## Setting up replication
    ## ref: https://github.com/bitnami/bitnami-docker-mongodb#setting-up-a-replication
    #
    replicaSet:
      enabled: true

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        cpu: 100m
        memory: 128M

    ## Affinity
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: Exists
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mongodb
            topologyKey: kubernetes.io/hostname

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true

      ## mongodb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClass: standard-expandable
      accessModes:
        - ReadWriteOnce
      size: 8Gi

    configmap:
      net:
        bindIpAll: true
        bindIp: 0.0.0.0

    ## Prometheus Exporter / Metrics
    ##
    metrics:
      enabled: true

      image:
        tag: 0.10.0-debian-9-r49
        pullPolicy: IfNotPresent

      ## Metrics exporter pod Annotation
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
