apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: default
spec:
  encryptedData:
    accesskey: AgBmKz+W/c4VZZy2taBMhK67/GMqpKEsFWQiROd7zdni6a6azPhlQ7sg9ZCWcB9dnyxO2MUDifal/04RVsdbsgnP3RuyuEn9wgeFxbtay2k2gaX329Rhmjc/OPht6FSWd/7ajMfCHUNL9U7GId7wd36LF4ublsnjJeXwJU2j5Df6E78QD75zYthOHo2bUj5kHJ3SQvFoOzBCklIXgcFOxeyoZ+CwOAzdHeYbCoI+AdG7o40tkEevmcG1wHvyxacy4bhSX6etM9ifnRHwyiXLiWTQ+pZHcslvxaSq/4JJzLtdC9X4mMminmqIBjUGMOWlStVE2KbeB3eBUKZ32ZeCksHu7EnZxJEtO4gwPac+ZjZ0UbH/WE/2i7HkPWO3S6uNLQiVOdSFzqmeG/6ORp8jPf4C+4TO6KqdPSPrUE7mQG50QrIQQRkghickcoEhNUYJbaUg1tBv5+3TsezZVkF74YtvNsHr2svOIjqJlFK6W/In1dwc5sEs8al2nWFgl74FboOK79DRo/X0VQiPd3PenKWENknEcEU/36D8pYQvcnx7gm2dDpvntUvavYtUwkTmnPXj2ibz9wk+z0Jm9AIplrsQI/RnYQlopapaqq0MfYmCrb4GjU6++Oa37wZAf88AUe56gMuUhPhpLmIrlTnVRgBBTQo8MA3wfOHJd6GaNCx3CsxqcCPAbvcnICCCR1qz87Jpipp2pw==
    secretkey: AgBKIcPcp6DnU+37mlr6oRy43SmYpaEqsRiGFJ2ecxlgCKA5yZNMvrXCH5YF+95SHHsXVuvKhYHZAYM6N9EzPV9c41rx9CYt0gR5SPa3c3fzsJWQl0ZiSqgqFDYLqD+LRtaq/s6N5F4uYyVZiSmFn1hMkcbYavf8Sl1GT0ujVbaMgNhkqymkWZBO+53zPt6HIwlSa87e8hVVewVRsPAiv/mOdgubESPoh+zLfTTjghkYCwmCx//b+XgL1Wi19El7Pj3HUzaQX1Gmr1GPma84GyvfhstdPeftNhHe7Moxb2vHms2aPoSx5C2kBe/gP1do2Hi0aIC1ruJLbvVS4mpVMAfSuGT89I8WCT8EvKHPzJzHoAyZYPE5TkpOh8lL44iVClSm2EJ7d8oUHG6PjHFea2+M17tNPRP1okL6BO0RS7yrr3zFEmmrCDqLT3bTtwhKymFNlX9IqESwOJsum0bE094yL/z2srYEIiRxvNQ0y2UFs6Xju1dn5GhWchHqoCk5iWh5/8C/g9aYR0KuELmNqp7yyhQSirwaRYy3OAHSHVF7kmahPR0jX+0cUUO19OI3F29jgX8WWcwLPNZc1RXvgw0DXRueDx3Ofa+wV+5HEsewiAWULn7UZJv6VggNbhBQvMZxPT2SJq2ZiRzc5B7ZeEx80/8vUTnY475BDDSZZkPCH6d+E/xMRbl0S05kJyDtR+wMAo/LShwYkv3QD/d1
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: default
    type: Opaque
status: {}

