version: '2.1'
services:
  application:
    depends_on:
      - mongo_healthcheck
    environment:
      - JWT_SECRET
      - KAFKA_CONNECTION_STRING
      - MINIO_CONNECTION_STRING
      - MONGO_CONNECTION_STRING
      - RABBITMQ_CONNECTION_STRING
    links:
      - dind
      - kafka
      - minio
      - mongo
      - rabbitmq
      - registry
    ports:
      - 3005:3000
    working_dir: /usr/src/app/applications/release-api/
