paths:
  /passwords:
    post:
      summary: Create
      tags: [Password Service]
      description: Creates a new record for the calling User.
      security:
        - AccessToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                plaintext:
                  type: string
      responses:
        200:
          description: OK
