apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafdrop-environment-variables
  namespace: default
spec:
  encryptedData:
    KAFKA_BROKERCONNECT: AgA9vfFwpY6Gkj3wYA269e3HGARabXlZFMuoei4jFmsKG+K1RyTTonpEUPOTJbhNp8bovecfNlnMiZlLNJmNAnWTNY3zSWQNWi4olXABwkZyFmj0jRzb/ieyrOSPaK0d+PrU9ft3PddY+1CWNNemJHGljUunIfqIv6z0xY4mccJH9X5q43IZ77Bi3eO+A0QTRmSJ4YtGPFqCFIG+YFtt5Zvkra7Amd3X1S9t7lRZXxZTm5HIWl82iLxXUB+5aDqHxIu8MnKH6WPUZX+Q9wTfEGySYXCrClFC2NdIJ2pfwNYwVtEi6V3PHvugtDhT3j+S36Bfu+jSceQ8i7E2nFhEP6FCPTl2BTcecyYnkHhUiy4Kk4z9+/pmc0KOhobTha6/IMCA2j3PjUQpM7z7f+NQpCVh8w6Si6I/e6y9kua6L2Dxajp/sBR+hx+xbiYhxoCalhU4QomIwkv79lSV6ldtZTO9Tbd/oPw9/PhofMfD6JB002fKtMz7wU5qBnr3hP5nYG8P0Vmu9+hq7t0uYuWnoOgJY8lVEOuYiocMQv2/r03CBabzhreRpPJDnHdSzSoOMdlre43iYDJWydw7d8sGjftijYDM3ry13NmvqUQCNiFoaZ+EKCtChPr0pdTxFmIVb2Q58C0dxrnnnsPwEKy4j3xylh+f17ZS38YzJ25QXJ5icY6hovnjbPGkNHbX5eDGIuoGcDEY4lp38BTWjseunVbutH8+oYLy5oL93QRX/WcnrhEUamXZsHepb8Z0O+0oO3ffRjMHAtbhol0hmshivlzuyXr/3dySdamNHvAAohnBm6lZXA==
  template:
    metadata:
      creationTimestamp: null
      name: kafdrop-environment-variables
      namespace: default
    type: Opaque
status: {}

