version: '3'
services:
  application:
    environment:
      - MONGO_CONNECTION_STRING
    links:
      - mongo
    working_dir: /usr/src/app/applications/password-service/
  mongo:
    image: mongo:4
