apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongoku-environment-variables
  namespace: default
spec:
  encryptedData:
    MONGOKU_DEFAULT_HOST: AgCWYmLWgnwfaSz6ft5WHvKeSHzuAV74jByYdygVjfUmVBdOptEd09O64A7sPvw4dxdpldsM3auoDuG6teIZelvQGmvHDnIntTi4ciZXvG9t+RzUFWR3afHLzeAO8OXaLtyM3Th7D/oV+wcjQvbOVZo3fmiB4z22/rmBQQoxewPbUY1roslF/WbdCLGiccMDqPYkyRmD1ByaqbKPhVl2+4DovyeQdwkQ6ish3+k/EabrmXt8MqoZmZ5bVd3qB7czgKbAD9UESbeljsYjb1xHkGRETQ+Tm5ZwR2lD4g3ZNl7A7cebhLRq+TVvgfgVwnQfIdtLakXZheHPdZjan6XAJDTlkqKNGXmuHTLCS+ZD+JYxtS8JPqN0S749G0JxDFVPsKzXYUlzEnCwUDvLeih2tIFOMXyWwQhpM8T1YUUGUAdh4Hp8adlEuehxABE0Y50MFssKv0Cvbsj+hON+gt/cDB2l0NaZOf09MErsTU3xpqkytr4SXpLWOfJqKwG8ocwM+yZg3+h0uAPiCsixDciqltHuyugfmWG+HhFA244R4V9OwcqgxxA5+W7QewDRIUT1M3AFI0z5E+lI3dYWHs3F3Dk2mg8Leq8LLZ5ryVlsSmdZ8uYn9fdY8B/bzTC5EWxSg3mivt1Rz7bWAlYzle48Q02ZF22PDfFrs8jogYP3QRT4fRlfJk9a83z9Qgs/r2rNqNjUsdkZE8/VHSUmo7LIgVl5IVPSHTb9FGiwEzQa+lGMgs/V9xLCuAQLy7H4CjKcjGbRe5Aet5W+vHuz60xNNsb80G1Szav2Fy6Dnva3ajQ5WZxqfJ2Jcpn2q1v+YUMHwdXpOg/O9zpckn0nvX2Rfooc7QFQSPzN5Xu+BF/yDsKsfB+ZFp80WqsTPEH7HHlIWAtCMUBL9+s9gYJQDh/dDpYYsxsW6UM4K8TGyl6h32jdSTwa5r5xZ9fw8aPygI5U81CebrspDHWxGWyNnqjA4iR2rQ3PbX6yIzeMRdUU4BJdvesdbWVgiO30GdnMVuCYi4zfm7Bl+29zxfddOH2aNAgauHiq3P1YIFou2KGu1loLi+ZuGEReQ1oWJHW7AWsLAVnEEgT+AsUikWVnOeTn0eV/1ZhWsVcttToKrEIf
  template:
    metadata:
      creationTimestamp: null
      name: mongoku-environment-variables
      namespace: default
    type: Opaque
status: {}

