apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: database-api-mongodb-replicaset
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: database-api-mongodb-replicaset
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    path: stable/mongodb-replicaset
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: Exists
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - mongodb-replicaset
            topologyKey: kubernetes.io/hostname
    image:
      tag: 4.0
    metrics:
      enabled: true
    persistentVolume:
      storageClass: standard-expandable
    replicas: 3
    resources:
      requests:
        memory: 128M
        cpu: 100m
