apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: database-api-rabbitmq
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: database-api-rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq-ha
    version: 1.36.4
  values:
    nodeSelector:
      cloud.google.com/gke-preemptible: "true"
    persistentVolume:
      enabled: true
      storageClass: standard-expandable
    podAntiAffinity: hard
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    prometheus:
      exporter:
        enabled: true
    replicaCount: 3
    resources:
      requests:
        memory: 128M
        cpu: 50m
