apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namespace-api
  labels:
    app: namespace-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: namespace-api
    spec:
      containers:
        - name: namespace-api
          image: tenlastic/namespace-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
          envFrom:
            - secretRef:
                name: namespace-api-environment-variables
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: namespace-api
  labels:
    app: namespace-api
    service: namespace-api
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: namespace-api
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: namespace-api
spec:
  hosts:
    - namespace-api.tenlastic.com
  gateways:
    - istio-system/istio-autogenerated-k8s-ingress
  http:
    - route:
        - destination:
            host: namespace-api
            port:
              number: 3000
