version: '2.1'
services:
  application:
    depends_on:
      - mongo_healthcheck
    environment:
      - DOCKER_ENGINE_URL
      - JWT_SECRET
      - KAFKA_CONNECTION_STRING
      - MONGO_CONNECTION_STRING
    links:
      - dind
      - kafka
      - mongo
    ports:
      - 3007:3000
    working_dir: /usr/src/app/applications/game-server-api/
