apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: launcher-ui
  labels:
    app: launcher-ui
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: launcher-ui
        version: 0.0.11
    spec:
      containers:
        - name: launcher-ui
          image: tenlastic/launcher-ui:0.0.11
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: launcher-ui
  labels:
    app: launcher-ui
    service: launcher-ui
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: launcher-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: launcher-ui
spec:
  hosts:
    - www.tenlastic.com
  gateways:
    - istio-system/istio-autogenerated-k8s-ingress
  http:
    - route:
        - destination:
            host: launcher-ui
            port:
              number: 80
