version: '3'
services:
  application:
    environment:
      - MONGO_CONNECTION_STRING
    links:
      - mongo
    working_dir: /usr/src/app/modules/change-data-capture-module/
  mongo:
    image: mongo:4
