components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        activatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        email:
          type: string
          format: email
        level:
          type: integer
        password:
          type: string
        updatedAt:
          type: string
          format: date-time
        username:
          type: string
