components:
  schemas:
    User:
      type: object
      properties:
        activatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        email:
          type: string
          format: email
        level:
          type: integer
        updatedAt:
          type: string
          format: date-time
        username:
          type: string
