apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: argo-ci
  labels:
    app: argo-ci
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: argo-ci
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
      containers:
        - name: argo-ci
          image: argoproj/argoci:latest
          env:
            - name: IN_CLUSTER
              value: "true"
            - name: WORKFLOWS_NAMESPACE
              value: default
            - name: NAMESPACE
              value: default
            - name: ARGO_CI_IMAGE
              value: "argoproj/argoci:latest"
          ports:
            - containerPort: 8001
            - containerPort: 8002
          resources:
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: argo-ci
  labels:
    app: argo-ci
    service: argo-ci
spec:
  ports:
    - port: 8001
      name: http
  selector:
    app: argo-ci
