galley:
  replicaCount: 3
gateways:
  istio-ingressgateway:
    autoscaleMax: 5
    autoscaleMin: 3
    sds:
      enabled: true
global:
  defaultNodeSelector:
    cloud.google.com/gke-preemptible: 'true'
  k8sIngress:
    enabled: true
    enableHttps: true
kiali:
  dashboard:
    grafanaURL: http://grafana:3000
    jaegerURL: http://jaeger-query:16686
  enabled: true
mixer:
  policy:
    autoscaleMax: 5
    autoscaleMin: 3
    replicaCount: 3
  telemetry:
    autoscaleMax: 5
    autoscaleMin: 3
    replicaCount: 3
    resources:
      requests:
        cpu: 200m
        memory: 256M
pilot:
  autoscaleMax: 5
  autoscaleMin: 3
  resources:
    requests:
      cpu: 200m
      memory: 256M
tracing:
  enabled: true
