version: 2.1

jobs:
  angular:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./projects/angular/package.json" }}
      - run:
          name: Install Node Modules
          command: npm install
          working_directory: ./projects/angular/
      - run:
          name: Lerna Bootstrap
          command: npm run lerna bootstrap
          working_directory: ./projects/angular/
      - save_cache:
          key: dependency-cache-{{ checksum "./projects/angular/package.json" }}
          paths:
            - ./projects/angular/node_modules/
      - run:
          name: Lint
          command: npm run lerna run lint
          working_directory: ./projects/angular/
      - run:
          name: Build
          command: npm run lerna run build
          working_directory: ./projects/angular/
      - run:
          name: Test
          command: npm run lerna run -- --concurrency 1 test:ci -- -- --code-coverage
          working_directory: ./projects/angular/
  nodejs:
    docker:
      - image: node:10
      - image: wurstmeister/kafka:latest
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: mongo:4
      - image: rabbitmq:latest
      - image: wurstmeister/zookeeper:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./projects/nodejs/package.json" }}
      - run:
          name: Install Node Modules
          command: npm install
          working_directory: ./projects/nodejs/
      - run:
          name: Lerna Bootstrap
          command: npm run lerna bootstrap
          working_directory: ./projects/nodejs/
      - save_cache:
          key: dependency-cache-{{ checksum "./projects/nodejs/package.json" }}
          paths:
            - ./projects/nodejs/node_modules/
      - run:
          name: Lint
          command: npm run lerna run lint
          working_directory: ./projects/nodejs/
      - run:
          name: Build
          command: npm run lerna run build
          working_directory: ./projects/nodejs/
      - run:
          name: Test
          command: npm run lerna run -- --concurrency 1 test -- -- --coverage
          working_directory: ./projects/nodejs/
      - run:
          name: Merge Test Results
          command: npm run merge:junit
          working_directory: ./projects/nodejs/
          when: always
      - run:
          name: Merge Code Coverage
          command: npm run merge:coverage
          working_directory: ./projects/nodejs/
          when: always
      - run:
          name: Merge Mochawesome
          command: npm run merge:mochawesome
          working_directory: ./projects/nodejs/
          when: always
      - store_test_results:
          path: ./projects/nodejs/test-results/
      - store_artifacts:
          path: ./projects/nodejs/test-results/
          destination: test-results
      - persist_directory:
          label: Persist Assets
          from: ./projects/nodejs/*
          to: /tmp/workspace/nodejs/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - nodejs
  publish_nodejs:
    docker:
      - image: node:10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Publish NodeJS Modules
          command: npm run lerna -- publish --exact --tag-version-prefix nodejs-v --yes patch
          working_directory: /tmp/workspace/nodejs/

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - angular
      - nodejs:
          context: open-platform-review
      - publish_nodejs:
          filters:
            branches:
              only: master
          requires:
            - angular
            - nodejs
