apiVersion: v1
kind: Pod
metadata:
  name: node
  labels:
    name: node
spec:
  containers:
    - name: node
      image: circleci/node:10-browsers
      command:
        - /bin/bash
        - -c
        - --
        - while true; do sleep 30; done;
      volumeMounts:
        - name: app
          mountPath: /usr/src/app/
      workingDir: /usr/src/app/
    - name: dind
      image: docker:19.03.8-dind
      command:
        - "dockerd"
        - "--host"
        - "tcp://0.0.0.0:2375"
      securityContext:
        privileged: true
    - name: docker-registry
      image: registry:latest
    - name: kafka
      image: wurstmeister/kafka:latest
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: localhost
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
    - name: mongo
      image: tenlastic/mongo-replica-set:latest
      env:
        - name: REPLICA_SET_HOSTNAME
          value: localhost
    - name: minio
      image: minio/minio:latest
      command:
        - minio
        - server
        - /data
    - name: rabbitmq
      image: rabbitmq
    - name: zookeeper
      image: wurstmeister/zookeeper:latest
  volumes:
    - name: app
      hostPath:
        path: /c/open-platform/
