gateways:
  istio-ingressgateway:
    sds:
      enabled: true
global:
  defaultNodeSelector:
    cloud.google.com/gke-nodepool : default-pool
  k8sIngress:
    enabled: true
    enableHttps: true
grafana:
  enabled: true
kiali:
  dashboard:
    grafanaURL: http://grafana:3000
    jaegerURL: http://jaeger-query:16686
  enabled: true
tracing:
  enabled: true
