affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: DoesNotExist
      weight: 100
persistence:
  storageClass: standard-expandable
prometheus:
  kafka:
    enabled: true
  jmx:
    enabled: true
replicas: 3
resources:
  requests:
    memory: 128M
    cpu: 100m
zookeeper:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: DoesNotExist
        weight: 100
  resources:
    requests:
      memory: 128M
      cpu: 100m
