affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: DoesNotExist
      weight: 100
mode: distributed
persistence:
  storageClass: standard-expandable
podAnnotations:
  prometheus.io/path: /minio/prometheus/metrics
  prometheus.io/port: '9000'
  prometheus.io/scrape: 'true'
resources:
  requests:
    memory: 128M
    cpu: 100m
