affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: DoesNotExist
      weight: 100
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app: mongodb-replicaset
        topologyKey: kubernetes.io/hostname
      weight: 100
image:
  tag: 4.0
metrics:
  enabled: true
persistentVolume:
  storageClass: standard-expandable
replicas: 3
resources:
  requests:
    memory: 128M
    cpu: 100m
