affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app: mongodb-replicaset
        topologyKey: kubernetes.io/hostname
      weight: 100
image:
  tag: 4.0
metrics:
  enabled: true
nodeSelector:
  cloud.google.com/gke-nodepool: default-pool
persistentVolume:
  storageClass: standard-expandable
replicas: 3
resources:
  requests:
    memory: 128M
    cpu: 100m
