affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: Exists
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - mongodb-replicaset
        topologyKey: kubernetes.io/hostname
image:
  tag: 4.0
metrics:
  enabled: true
persistentVolume:
  storageClass: standard-expandable
replicas: 3
resources:
  requests:
    memory: 128M
    cpu: 100m
