affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: DoesNotExist
      weight: 100
exporter:
  enabled: true
  tag: v0.34.0
replicas: 1
tag: 5.0
redis:
  resources:
    requests:
      memory: 128M
      cpu: 100m
sentinel:
  resources:
    requests:
      memory: 128M
      cpu: 100m
