paths:
  /games/{gameId}/articles/count:
    get:
      summary: Count
      tags: [Articles]
      description: Returns the number of matching records for the query.
      security:
        - AccessToken: []
      parameters:
        - in: path
          name: gameId
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
