kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: continuous-integration-angular-node-modules
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: continuous-integration-nodejs-node-modules
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
