paths:
  /users/login/token:
    post:
      summary: Log In with Token
      tags: [User Service]
      description: Uses a valid JWT to log in.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
