galley:
  replicaCount: 3
gateways:
  istio-ingressgateway:
    autoscaleMax: 5
    autoscaleMin: 3
    sds:
      enabled: true
global:
  defaultNodeSelector:
    cloud.google.com/gke-nodepool: preemptible-pool
  k8sIngress:
    enabled: true
    enableHttps: true
kiali:
  dashboard:
    grafanaURL: https://grafana.tenlastic.com
  enabled: true
  replicaCount: 3
mixer:
  policy:
    autoscaleMax: 5
    autoscaleMin: 3
    replicaCount: 3
  telemetry:
    autoscaleMax: 5
    autoscaleMin: 3
    replicaCount: 3
    resources:
      requests:
        cpu: 200m
        memory: 256M
pilot:
  autoscaleMax: 5
  autoscaleMin: 3
  resources:
    requests:
      cpu: 200m
      memory: 256M
prometheus:
  replicaCount: 3
security:
  replicaCount: 3
sidecarInjectorWebhook:
  replicaCount: 3
