components:
  schemas:
    Collection:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        databaseId:
          type: string
        jsonSchema:
          type: string
        name:
          type: string
        updatedAt:
          type: string
          format: date-time
