version: '2.1'
services:
  application:
    depends_on:
      - mongo_healthcheck
      - rabbitmq
    image: node:10
    links:
      - mongo
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
  mongo:
    build:
      context: ./dockerfiles/mongo-replica-set
    environment:
      - REPLICA_SET_HOSTNAME=mongo
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
  mongo_healthcheck:
    image: busybox:latest
    depends_on:
      mongo:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
