components:
  schemas:
    Collection:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        databaseId:
          type: string
        indexes:
          type: array
          items:
            type: object
            properties:
              key:
                type: object
              options:
                type: object
        jsonSchema:
          type: object
        name:
          type: string
        updatedAt:
          type: string
          format: date-time
