apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'tenlastic.com'
    - '*.tenlastic.com'
    - '*.staging.tenlastic.com'
    - '*.test.tenlastic.com'
  acme:
    config:
    - dns01:
        provider: cloud-dns
      domains:
      - 'tenlastic.com'
      - '*.tenlastic.com'
      - '*.staging.tenlastic.com'
      - '*.test.tenlastic.com'
