paths:
  /databases/{databaseId}/collections/{collectionId}/{id}:
    delete:
      summary: Delete
      tags: [Records]
      description: Deletes an existing record.
      security:
        - AccessToken: []
      parameters:
        - in: path
          name: collectionId
          schema:
            type: string
          required: true
        - in: path
          name: databaseId
          schema:
            type: string
          required: true
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    $ref: '#/components/schemas/Record'
