paths:
  /users/password-reset/password:
    put:
      summary: Reset Password with Password
      tags: [User Service]
      description: Updates an account password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - newPassword
                - password
              properties:
                email:
                  type: string
                  format: email
                newPassword:
                  type: string
                  format: password
                password:
                  type: string
                  format: password
      responses:
        204:
          description: No Content
