paths:
  /passwords:
    put:
      summary: Update
      tags: [Password Service]
      description: Updates an existing record.
      security:
        - AccessToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPlaintext:
                  type: string
                newPlaintext:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    $ref: '#/components/schemas/Password'
