apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  dnsNames:
    - "tenlastic.com"
    - "*.tenlastic.com"
    - "*.staging.tenlastic.com"
    - "*.test.tenlastic.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: istio-ingressgateway-certs
