apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    passphrase: AgARgSDqsSwlNPVOPIcalkuc41ee3hz28mNzSJDLlnRuSs9kd8fzAJW4dFHxy/5plqrCKDggEN5eRJzydWOSMSC9T46zDmulhwhv3VQqtVZOhZNruiJGnktAsIL/5IQYRho/PaOPcBBCGvMJdkqcjLLtjhoR15wBdLTD5wW0xSDx1mn11IV8LFmQa6nTbJb6UCJc3HwKCZojRsmStDjoDce//1Vn5jQXkJcrDaQEnmbLGVGnHQo0dIwyRhv2+i5sOEih/Ge2H5PMi2szqWoyAvD73sKy07MrryPec+XBTgwWhwuOG9aaDiV5p1j+078n7nc/kZYmAdIp99VmIkerpeRwoIwb48q+ow8sJUaMcmc99Umc90YL4Pit65pRtZQH0jBg4AaG+q8KmflCi8eM/DiF2d2s1iIZpfKSTi9xmrh1MPRzxYkjQe7a39kHBqUESBpGNzCsZ+0bp32tsVQy82v3CHtXwhK3ywE6ntT0RyKhM6xx0gQrFsy/svwrAXDXsfPdo1WFyb3Os6lb8IXmINhBr1rSHLESi3GBoXasRbTW93lwmdKBQnuuxpS0T9MbFmsXKqFVSvELg9sWl0lVvU4MJ2LUHslYdOdGos1h3vUB3Ugr7QCQWFRtkD4L1eXsqsNtyaGSm//UhXgXAVUaFUyjEGZLDh0OuoXu1PI/4sQNMZITGO7Mf633kHZ6K6K7WMtM5Pm9rVJuPzjoN3A0
    username: AgBIZxSACvcjWJ1klFJk/wOf0h5pBxuNfjqPMtb5dMaiIK0BYSWXTVR1joV6qfJJwc7XjzOK5zoY/qhzPg3YRUnPx5q8ejyUmHVebxAYUDjh115wEPYPdRxjAXTpuIIOeWmWygcdj6rpw5IBnxMcBbuO0mbBvaewuqzGlSuBDH/YitOz0ZYgUdB8xONJ6pHA4gDtA734dqSbvVb8kmmKSalpI0b94bKGn1BCDbJ0oR0/AriqDoP9MV6uivygGyLHDq+tuCILohGaOcm/ft7k66bQKbFanEMhzunOOlPDOvV+ML8E2D44hBF3Mdc7h9qtoaVF11Gtl0tgQMqTNuUhrZjUUlzu0Thoe8MK5jRXj1BZEkFplLvP94diT+mEOgcgfdMpxIRgHUZUOYa/JlM6wSouVNsqIIMoh0c0xKUx/mnHitLHbf2XPBcKTxrdhnVFtwCJU29bHnMBLFclG4DptbVB496Ek89JqFo4eBaG7R5pDR84PhBcwnxySi4iVeGE8isKSoeQSOJv7KsaaF5DH5OFlbULLG9lGPFxLuHCF86ySWpdRytjwcsW5liFrdVIFJ0PYKljI/rr1itTzittm0IRqELqoLGeHx8P8QYy5PwNAE0ClZx5XskvWTtvYBPYUkF2mwcKk+jd/rIFT02dxGIs4mTp7SBr41NtBDAtFA1G9iKvQCivffjenpkXEL8GQKbpg393Uw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kiali
      name: kiali
      namespace: istio-system
    type: Opaque
status: {}

