apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: default
spec:
  encryptedData:
    accessKey: AgBE8E3XTfsSzccgsWqWrw+27pShO3MTbdCp5SgZJ1poqdOmtBn7Iu8oTKXkzPQDP+3I8bVDofdl5kiD1QueVWRRwt7gq1DANseJgI/dfeXugQblMt/BSUbELKstna7aS8SFLBSPQIabl1FRQJMYT9hVM1IA8R0yO1y8kYUNVXvnsypcmBr57VPgdVvxQCCE2SGr21uSN8VSSIUGO4DsAjbGJMPOK9+HGv+F6sVZPNEmN0hYZlHqOtHUnK9xx3QWQE0Gaz16HBKmG0JV9Uhiw4wlXwdQRmseoO1x/exUIFLHZJGd6i904YRvvpiWgi07FrXBJGcbPPrTaOopOCNztTHtKn+NPRo5PB1WzPP/E1hYXYWfUjpB/RHNGGw8z+U5pXWcdpe7uqKmmSZ8+EuPFGXpxFmv45aZUCI3x+frudCov1U5qeIpRu/6ml4/0+J6pcwOJ8+FSbFxxMzftCU61CY6GcdVQoUmUmn1h8sGmNcWQQ0RhjQqwD6+DFLHsV6PwrJHbJI1WLAXqKwfJDfHaUGQydCO0RAPpsApwIgKnuGxU01kyg6wewrIrd8Yo2+8Dt+HROBdx/wjnHkorQqYkvNdAYoElOXIdWp7sblYDFv11uzZXnvDz3f3ZozUv1mZImAyEW3RuPLAjk6rK+U3982UqMxKlw3ynsOK0R4VNa4+x0bOK6FiClZ5A496AjLFby1eRFkfDw==
    secretKey: AgA0MK2WsQSSuXI/7oEOmqlA6HTJB7zOy8ES/hpshGqSiy/U3Utg9IQF4L9CcVLN5IQrx7RquAMwsD9DwVPgQyv/LtgTFryKsoFHwROqj05/twQRqc55c8sLUX+oIcrIoa9xUhVuLScGfWXmRsAhFXBb0L/vwRyxfdsq9JDH73Mdw+5l1k5bnjbAst90IFu0OGz3ULUWh3SlIiHtK/9Hpt9ViEwyUOI7NhD2xvDOmuOurUIRk3kMhKapb9ojnJ0hOxSEQoVvuygakif76g9ghBboZnNQ9usNl9QnCfR6O43ug3FCu9xKD6qQLhsXnpVFNV1bxUklHN2tH/a0V6goX6KlA6onet+ZgzMq5TbALeqvLlp9OHkhJGoQIQc7BcOWCtCUAqMdEGcEgZldu3z4WAjpuqrUCGKWPF55JJ76T0h8Sbxzp9bWfOr3Yy1uCAOteovEJAHW7b+jaeVkKzioKjvGxfT8wFEcqkg1MP6mOHsJTqmqp+xLhuParLHEDSCiuvsEU+OryqefS90zts9sK7h5y+IM8zG+wXNJb/knNs19k7jneqSPBBu2LtIlg9NhFI8FZEsCUTYQ1BPW9rgEJMqqLLvBfJ0Sf9mQzRFs5ItKqoq1c4AXBgdDcmUm2arqDQmnRy/Y7524h+Ln76DuIYsY+FzDwwEkBIqmILR34L0WIaowit3PxrNRWnJ/eeLPygLziIoxogYWOWhOluSH
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: default
    type: Opaque
status: {}

