apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portal-ui
  labels:
    app: portal-ui
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: portal-ui
        version: 0.0.13
    spec:
      containers:
        - name: portal-ui
          image: tenlastic/portal-ui:0.0.13
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: portal-ui
  labels:
    app: portal-ui
    service: portal-ui
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: portal-ui
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portal-ui
spec:
  hosts:
    - portal.tenlastic.com
  gateways:
    - istio-system/istio-autogenerated-k8s-ingress
  http:
    - route:
        - destination:
            host: portal-ui
            port:
              number: 80
