paths:
  /databases/{databaseId}/collections/{collectionId}/{id}:
    put:
      summary: Update
      tags: [Records]
      description: Updates an existing record.
      security:
        - AccessToken: []
      parameters:
        - in: path
          name: collectionId
          schema:
            type: string
          required: true
        - in: path
          name: databaseId
          schema:
            type: string
          required: true
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  record:
                    $ref: '#/components/schemas/Record'
