service: email-service

plugins:
  - serverless-webpack
  - serverless-offline-sns
  - serverless-offline

custom:
  serverless-offline-sns:
    sns-subscribe-endpoint: 127.0.0.1
    sns-endpoint: http://127.0.0.1:4575
  webpack:
    packager: yarn
    webpackConfig: ../../webpack.config.js

# Out of Memory Issue: https://github.com/serverless-heaven/serverless-webpack/issues/299
# package:
#   individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'test'}
  memorySize: 1024
  timeout: 5
  stackName: ${self:service}
  environment:
    PASSWORD_RESET_URL: ${self:env.PASSWORD_RESET_URL}
    STAGE: ${self:provider.stage}

functions:
  activation:
    name: ${self:provider.stackName}-activation
    handler: src/handlers/activation/index.handler
    events:
      - sns:
          topicName: users
          displayName: users
          filterPolicy:
            action:
              - create
              - update
            modified:
              - activatedAt
  password-reset:
    name: ${self:provider.stackName}-password-reset
    handler: src/handlers/password-reset/index.handler
    events:
      - sns:
          topicName: users
          displayName: users
          filterPolicy:
            action:
              - create
              - update
            modified:
              - resetHash
