apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-credentials
  namespace: grafana
spec:
  encryptedData:
    password: AgCnOxpESfuXs3hyFPc73F2htmhapFlB0XQqlXYUN/A4kExoZgnLWc0cfyO91oNJk3PgfnkknOb0ybqtGGb1yL8PrdHlz7zpZyv4ypWEMjQU0MsodiEBmIzWi28g4tCRtbTGxATXGeDz5h9igtVPr6s3rRaMIF2t5C4OUe8haqljriDumynBIIQBPGlDk+mZ63vATRsxYESMAGdTGZRKa7oJ1yvSlQHfJZgobYKA5q6LEybybzAmPosprOQZSCetZT7E5qVV/FCoUr23IPTip5iyBHYv2AZ5F1NDFcHXOA4dJ09JpOlFvc6xGqarvWoSjRlKXG9qbNnrE0r0Q4KEq4nbNIHsj9IEwhU0OlOdUaEAc4Km7tjXPr9VrMTVcEgic+Iu6LrTFRhgjK6X4HZ56jC4IBuiLUDh9BVJ1msR1eHxDkerHV9cNz1xkK/Qq1Js8FSFNLXOOT0lj4L4dc6M7qpATVWpR4B+Bnepsb/WaCeohICqQYTPyMXhRx8geofg/VEIaF4jyORPkjlkyT9bfHsyeBy6dXwNpzJO+8UTtrNMlubuFn2txje+nlHQP4Sn1Z6/i4jxayb+YakqLQ7k9wYypXtSFa+xk1ds+rnSa82R3EFoQ3ULDoTP3usn0SfPopxRAWirDP3aOz/M3PrMPIN5/+CjOoL0Phi9oKcxKhrJa6KrsriQo8LXvhgtGOimHADIx3ODM82SDgzwIwLd
    username: AgAzRpSmLSio6apduY9ivLs7j3A3OwAjZWETaYP/YSwZZvD6zEfgdEAjqy5ca3wHRvp5zNR5A5xKsH2jJw0moTQEosOqYKtpa8WVrGtW/Sw6Wmg0sUFwg2Xgv/+f50oyuZiOTSED7jJ3GU7NYDu6/UKxhQdfCX4AhD7GJ1nv+fIlQ/gXOyF4+eE7MDd9gDNpO08aGT1dvbmUvhG4vNQW7UhN/KCK2oMEsTZMm686wdQ/RYaNV3QcomzDn7Uhs9vgZTHL5SuMotuo7Ob0r4REox3UNlnKFwWE6c5BiBu1JCNlF4Bpy1z6SSoVt+1utVF7zXJpLmRJTY1nsdDpuMZddW4nczfQRBrdWjrxpsGUXw43xZI9If0zPrwZYeKXOy1Be/GqpYaCYcwq7y1FHy+PbQJXmxKTeueT6nj74XqCFjsmTJuXIXZVG2eYd83qLil7X15nawqmKxMCfCRSI+QO+Mjockqk0LkQSLHf/FionHWbvU6WFazivt6byFaLNYBZ1FrJPZW+PoqUadR5ffm/1G278A3qi52v5PVfwGLn9EKxPNte5Uj4CeX9VllpxjmKZXV9Yojr49I3HHcYa7eRjuA9mnAUQpq/J1TsBeTMEtuqCcXjjjxF3oJqATCNwl1gBYZNAxvA/E0vya3zsfiK7fco+om/eqYdUuQNHOqvDH5wwlyz3415j7CTHYwWjhG4j0vos/0v2A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
      name: admin-credentials
      namespace: grafana
    type: Opaque
status: {}

