apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-secret
  namespace: default
spec:
  encryptedData:
    haSharedSecret: AgA5kNYUzHK/5hxm8LkyQ2Vd2//gaXyv+dpLDS2NoKa5/7FU/lnbUc+4ErDIP3pXkDirDuHsjxfpWeVIsEwsemp8ZVki5qd4K8RTAjsUP5ZivpYvnE4CO5A95HsxJmrcbQJuRG7nyX4pbKxGoNXD9TWSLHbYvfn6H6Gh9IHT8OhUdksvi2rhdrJ8HXJv5heiTuLUGQmNdHiz5MxQgr8Zat0B03jffYp/q1CLZLfkSKZbq3bZPPvxOa8CjNN7Z3T5HOCdbaMvpl6Cu2ucrG5wmcZR3mWrTV52kPrj6YgBkHGNlMZy0vL38KBQQEJGCUqCED3jYPXjQxHTcwQHoWw0inWdV4kW0QPAl76a9PY6qrQqAB4sZQqSDVBDAVdoCkIGAgWSU75/HzF25Xr/+5OnUl6f0mH0PZ0TJNtAMecVIMy6MkpO8IO4DaIuJaW6Gb/S2QHVmL5LKyHqUe0pRK2+IJfg6AY3nvGOzKJPHFlci+tgfPPazRcg0oj2K0kRTKuX0s8RbGde8VLhkfwGrPavBvYeHLOo+TEWp09bAEGvh8uS4a1Ob0gOfprOyYN6UXarJ8dFd52QjmU07Odcyhjy2ZZdlFEjIfCg6Fslmkd81gPnEBPo+EBlnqrZksRqLaxkIpNi0AO67GN4/g/A0617J8dMuaE2GuVHqXmSnR/pZkXJRN7ZmR8aO3YO+Y7YjAYGXh+QffjW4RpToJ7OwtNJqEk=
    htpasswd: AgBtkFZZcMjpbx2OFn7iW+4kfMXAzql6ogVWNMKFq8o0LAeZwunZrFSrzHxUSyyRAxBbjz6kSzWkDLY7X3OKIpp1uhkYfVRG2bJM16kK7uiukwCCK3cLU0SQAf0rOfOZFzEB31klLvGHwL3bG9kBcDvtHIEtQEVDcQJO1539j5jlzPnbjIU+FWWHWj6U0lppkYKG5WS/TA9bh2BsO/3Un9wr4VH/drU+1XTVwhts/odXryh8gwENMV62M+F5MWfJqpKSW2cbB5HoAX4iljNPonpUiJ938XHtIZVfjnWT/v3Tl87OljBbDeChn3z6DthujZNKMKvnJRx6zQXiriZ8LTfYaWDp0stkBZBR4bFjjAYlVnb8qWk6/6VlaHhxbipAaM/ZBXnjTNAaiBSx87t4hb7sZVlx+uTDyV5xWw/T/TaclUGXpG/BNE76dsJ+hPU9Ry4xc94mVMDkVvDLUxedNiz8YSbD+n8ZxhleRGMR21hj77QS4MyPG9EdxB48AqJc3xwKV759eDVssea3RtWsiJidnp8YbkAL9IZKbVhBw5j14MMNwJxOGc0nvVc/u8EVkO2mgpdNeRZE0ZIku/zmDowU2+EYy6JZUeqYNCcSrODHAnWApTQ3Ur1WwYJfmiVCcIvpRIGPPU7MdWG8pUl9vIvyf3AI8k75ueExdEqLPMfaolRvg75+sRPSOcZIss3TXD9Qu9fVWx+CYlfbSLyqxtkagYgSZVxKxBjL13FS0Om1VYQKDXT85vImx236S5sEx5SFtguAGELhMy+h2i53YD8R634=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-registry
      name: docker-registry-secret
      namespace: default
    type: Opaque
status: {}

