paths:
  /users:
    get:
      summary: Find
      tags: [User Service]
      description: Finds records matching the search criteria.
      security:
        - AccessToken: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
