version: "3"
services:
  application:
    environment:
      - MONGO_CONNECTION_STRING
    links:
      - mongo
    ports:
      - 3000:3000
    working_dir: /usr/src/app/applications/user-service/
  mongo:
    image: mongo:4
