openapi: "3.0.0"
info:
  version: 1.0.0
  title: "User Service"
host: "localhost:3000"
basePath: "/"
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions: {}
responses: {}
